### ISSUE TITLE
NoMethodError: undefined method `destroyed?' on saving instance 

### ISSUE THREAD

**Issue by takashi** [k0kubun/activerecord-precount#19]
Hi, I'm suffering with this problem that title described with this gem.

For example, here's the test case that reproduce the error. (I wrote this test case in forked repo of activerecord-precount)

```ruby
require 'cases/helper'

class BugReportTest < ActiveRecord::CountLoader::TestCase
  def setup
    tweets_count.times do |i|
      tweet = Tweet.create
      i.times do |j|
        Favorite.create(tweet: tweet, user_id: j + 1)
      end
    end
  end

  def teardown
    [Tweet, Favorite].each(&:delete_all)
  end

  def tweets_count
    3
  end

  def test_save_break_with_count_loader_and_dependent_destroy
    tweet = Tweet.first
    tweet.my_favorites_count
    tweet.save!
  end
end
```

Then I got

```
NoMethodError: undefined method `destroyed?' for 0:Fixnum
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/autosave_association.rb:461:in `save_belongs_to_association'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/autosave_association.rb:202:in `block in add_autosave_association_callbacks'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/autosave_association.rb:158:in `instance_eval'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/autosave_association.rb:158:in `block in define_non_cyclic_method'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `call'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:770:in `call'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:770:in `block (2 levels) in deprecated_false_terminator'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:769:in `catch'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:769:in `block in deprecated_false_terminator'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `call'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/callbacks.rb:298:in `create_or_update'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/persistence.rb:152:in `save!'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/validations.rb:50:in `save!'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `block in save!'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:211:in `transaction'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/transactions.rb:324:in `save!'
    /Users/takashi/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-5.0.0.1/lib/active_record/suppressor.rb:45:in `save!'
    /Users/takashi/src/github.com/k0kubun/activerecord-precount/test/cases/associations/bug_reoprt_test.rb:24:in `test_save_break_with_count_loader_and_dependent_destroy'
```

This is because [the extended behavior of Reflection#load_target](https://github.com/k0kubun/activerecord-precount/blob/master/lib/active_record/precount/reflection_extension.rb#L6-L14) returns `integer` but [ActiveRecord:: AutosaveAssociation. save_belongs_to_association](https://github.com/rails/rails/blob/fe1f4b2ad56f010a4e9b93d547d63a15953d9dc2/activerecord/lib/active_record/autosave_association.rb#L465) expects ActiveRecord instance. 

I'd strongly like to use the gem but this is the blocker to use. 

Any solutions to solve this? 

Thanks.

**Comment by k0kubun** [comment]
Thank you for researching it.

Hmm... Without deep consideration, it looks better to have wrapper class for that, which should not consume much resource like ActiveRecord::Base instance, like struct with `#destroyed?` method. What do you think?

**Comment by takashi** [comment]
@k0kubun 

thanks for replaying.
I think we can override `AutosaveAssociation.save_belongs_to_association` in this gem like

```
 def save_belongs_to_association(reflection)
  return if reflection.is_a? ActiveRecord::Reflection::CountLoaderReflection
  super(reflection)
end
``` 

I think this way is simpler than to have wrapper struct class, wdyt?

**Comment by k0kubun** [comment]
Looks good. I prefer that way.

**Comment by takashi** [comment]
Thanks. So I'll send PR to add the patch above 🙏
