### ISSUE TITLE
Rails 5 - undefined method `match' for #<Class:0x007fc9b7a33378>

### ISSUE THREAD

**Issue by vemv** [k0kubun/activerecord-precount#21]
![image](https://cloud.githubusercontent.com/assets/1162994/20913810/2419e7d4-bb7b-11e6-9414-0b89e26506b7.png)

This is the problematic line:

```ruby
      def klass
        (@klass ||= active_record.send(:compute_type, options[:class_name] || name.to_s.sub(/_count\z/, '').singularize.classify)) rescue binding.pry
      end
```

I think the problem boils down to the fact that you're invoking a protected AR method.

Any hint?

Cheers - Victor

**Comment by k0kubun** [comment]
Thank you for reporting the issue. Could you show a full backtrace with not image but text?
And what kind of model or method call reproduces the error?

**Comment by vemv** [comment]
In my ocurrence, `options[:class_name]` wasn't an actual class name, but a class (e.g. `MyModel`).

So changing the method impl to 

`@klass ||= options[:class_name]`

did the trick.

And then your gem did its job, and saved me N+1 queries!

Let me know if I can help you debug this.

**Comment by vemv** [comment]
> Thank you for reporting the issue. Could you show a full backtrace with not image but text?
And what kind of model or method call reproduces the error?

For the attempt

` Design.includes(:user).precount(:votes).first`

I get:

```
Exception: NoMethodError: undefined method `match' for #<Class:0x007fd5eccdd128>
Did you mean?  catch
--
 0: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
 1: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/inheritance.rb:137:in `compute_type'
 2: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-precount-0.6.2/lib/active_record/precount/reflection_extension.rb:27:in `klass'
 3: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/association.rb:118:in `klass'
 4: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:163:in `block in grouped_records'
 5: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:159:in `each'
 6: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:159:in `grouped_records'
 7: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:148:in `preloaders_for_one'
 8: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:115:in `preloaders_on'
 9: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:102:in `block in preload'
10: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:101:in `each'
11: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:101:in `flat_map'
12: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/associations/preloader.rb:101:in `preload'
13: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:705:in `block in exec_queries'
14: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:704:in `each'
15: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:704:in `exec_queries'
16: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:580:in `load'
17: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:260:in `records'
18: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation.rb:256:in `to_a'
19: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:561:in `find_nth_with_limit'
20: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:590:in `find_nth_with_limit_and_offset'
21: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:543:in `find_nth'
22: /Users/vemv/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/relation/finder_methods.rb:122:in `first'
```

**Comment by k0kubun** [comment]
`class_name` should be String. http://guides.rubyonrails.org/association_basics.html

But this error message is a little hard to understand. We may need some fix for this.

**Comment by vemv** [comment]
> class_name should be String. 

Just in case - I don't pass any class_name option... the error seems to originate from the gem itself, when using Rails 5. Could it be the case?
