### ISSUE TITLE
Doesn't match with bullet Gem

### ISSUE THREAD

**Issue by gilangmugnirespaty** [k0kubun/activerecord-precount#29]
I encountered this when using this gem and bullet gem.

`.rvm/gems/ruby-2.2.3/gems/bullet-5.5.1/lib/bullet/ext/object.rb:12:in `primary_key_value'`

and I opened bullet gem to see that line code but got no idea.
[https://github.com/flyerhzm/bullet/blob/master/lib/bullet/ext/object.rb#L12](url)

Thanks
-Gilang

**Comment by k0kubun** [comment]
Please try latest version first before you report any issue. It seems already solved in 5.6.0 https://github.com/flyerhzm/bullet/pull/330
And you should provide full error backtrace when you have.

**Comment by falcon8823** [comment]
I encoutered same issue on activerecord-precount(0.7.0) with bullet(5.6.1).

### Framework Trace

```
bullet (5.6.1) lib/bullet/ext/object.rb:12:in `primary_key_value'
bullet (5.6.1) lib/bullet/detector/n_plus_one_query.rb:30:in `map'
bullet (5.6.1) lib/bullet/detector/n_plus_one_query.rb:30:in `add_possible_objects'
bullet (5.6.1) lib/bullet/active_record5.rb:198:in `target'
activerecord (5.1.2) lib/active_record/associations/singular_association.rb:10:in `reader'
activerecord (5.1.2) lib/active_record/associations/builder/association.rb:111:in `answers_count'
activerecord (5.1.2) lib/active_record/relation/delegation.rb:39:in `each'
activerecord (5.1.2) lib/active_record/relation/delegation.rb:39:in `each'
actionview (5.1.2) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.2) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.2) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.2) lib/action_view/template.rb:155:in `render'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.2) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.2) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.2) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.2) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.2) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.1.2) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
actionpack (5.1.2) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.2) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.2) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.2) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.2) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.2) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.2) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.2) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.2) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:46:in `block in serve'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.2) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.2) lib/action_dispatch/routing/route_set.rb:832:in `call'
bullet (5.6.1) lib/bullet/rack.rb:12:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.2) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.2) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.2) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.2) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.2) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by k0kubun** [comment]
Thank you for adding full backtrace. Could you also add exception class name and its message too?

**Comment by falcon8823** [comment]
It occurs on the line that is called `*_counter` method.

![screencapture-localhost-3000-universities-1504624063076](https://user-images.githubusercontent.com/362095/30068011-6a11cf88-9297-11e7-8376-86ec835a9264.png)

**Comment by k0kubun** [comment]
By the way, what do you think about https://github.com/k0kubun/activerecord-precounter ? Its internal design is much simpler and strong for bugs. I guess it works even with bullet. If you think it's enough for your use case, please use it instead.

**Comment by falcon8823** [comment]
Oh, I just start to use this gem now. I don't know the new one.

I saw your articles below.
http://k0kubun.hatenablog.com/entry/2015/07/15/225150

**Comment by falcon8823** [comment]
I try to use new one. Thanks for your awesome work!

**Comment by k0kubun** [comment]
Thank you for reading it. Well, I consider to update that article later.

Closing this for now. If you have trouble with new version, please file an issue in that repository :)

**Comment by falcon8823** [comment]
I failed to use new one because my project has `has_many through` and STI model.

So, I continue to use this gem.

I avoid facing this issue by adding `skip_bullet`.

https://github.com/flyerhzm/bullet#whitelist
